SickFriday/SickFriday/Controllers/ChartsController.cs
using SickFriday.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace SickFriday.Controllers
{
    public class ChartsController : Controller
    {
        //
        // GET: /Charts/
        private SickFridayDB db = new SickFridayDB();
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        public ActionResult Points()
        {
            List<string> xval = new List<string>();
            List<string> yval = new List<string>();


            foreach (var points in db.Users.ToList().OrderByDescending(c => c.Points).Take(9))
            {
                xval.Add(points.Name);
                yval.Add(points.Points.ToString());

            }

            string[] _xval = xval.ToArray();
            string[] _yval = yval.ToArray();

            var chartsPoint = new Chart(width: 1000, height: 400, theme: ChartTheme.Yellow) //,theme: ChartTheme.Yellow
            .AddSeries(
                xValue: _xval,
                yValues: _yval);

            return File(chartsPoint.GetBytes("png"), "image/png");

        }

        public ActionResult Presence()
        {
            List<string> xval = new List<string>();
            List<string> yval = new List<string>();

            foreach (var points in db.Users.ToList().OrderByDescending(c => c.Presence).Take(9))
            {
                xval.Add(points.Name);
                yval.Add(points.Presence.ToString());

            }

            string[] _xval = xval.ToArray();
            string[] _yval = yval.ToArray();

            var chartsPoint = new Chart(width: 1000, height: 400, theme: ChartTheme.Green) //,theme: ChartTheme.Green
            .AddSeries(
            name: "Anwesenheiten",
                xValue: _xval,
                yValues: _yval);

            return File(chartsPoint.GetBytes("png"), "image/png");

        }
        public ActionResult Input()
        {
            List<string> xval = new List<string>();
            List<string> yval = new List<string>();
            List<string> yval2 = new List<string>();

            foreach (var points in db.Users.ToList().OrderByDescending(c => c.Win).Take(9))
            {
                xval.Add(points.Name);
                yval.Add(points.Input.ToString());
                yval2.Add(points.Win.ToString());

            }

            string[] _xval = xval.ToArray();
            string[] _yval = yval.ToArray();
            string[] _yval2 = yval2.ToArray();

            var chartsPoint = new Chart(width: 1000, height: 400, theme: ChartTheme.Blue) //,theme: ChartTheme.Blue
            .AddSeries(
                name: "Buy-In",
                xValue: _xval,
                yValues: _yval
                )
            .AddSeries(
                name:"Gewonnen",
                xValue: _xval,
                yValues: _yval2)
            .AddLegend();

            return File(chartsPoint.GetBytes("png"), "image/png");

        }

	}
}

SickFriday/SickFriday/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SickFriday.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Anfragen bitte per Mail";

            return View();
        }

        public ActionResult Member()
        {
            return View();
        }


    }
}

SickFriday/SickFriday/Controllers/RankingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SickFriday.Models;

namespace SickFriday.Controllers
{
    public class RankingController : Controller
    {
        private SickFridayDB db = new SickFridayDB();

        // GET: /Ranking/
        public ActionResult Index(string searchString)
        {
            //string searchString = id;

            var UserList = new List<string>();

            var UserQuery = from d in db.Users
                            orderby d.Name
                            select d.Name;

            UserList.AddRange(UserQuery.Distinct());
            ViewBag.searchString = new SelectList(UserList);

            
            if (!String.IsNullOrEmpty(searchString))
            {
                var ranking = from m in db.Rankings
                              where m.First == searchString
                              || m.Second == searchString
                              || m.Third == searchString
                              || m.Fourth == searchString
                              || m.Fifth == searchString
                              || m.Sixth == searchString
                              || m.Seventh == searchString
                              || m.Eight == searchString
                              || m.Ninth == searchString
                              select m;

                return View(ranking.OrderBy(d => d.Date));

            }
            else
            {
                return View(db.Rankings.ToList().OrderBy(d => d.Date));
            }



            
            //return View(db.Rankings.ToList().OrderBy(d => d.Date));
        }

        // GET: /Ranking/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ranking ranking = db.Rankings.Find(id);
            if (ranking == null)
            {
                return HttpNotFound();
            }
            return View(ranking);
        }

        // GET: /Ranking/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Ranking/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,First,Second,Third,Fourth,Fifth,Sixth,Seventh,Eight,Ninth,Date,BuyIn,WinFirst,WinSecond,WinThird")] Ranking ranking, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                
                //update Ranking table
                db.Rankings.Add(ranking);
                db.SaveChanges();
                CreateOrUpdateUserRanking(ranking);
                //Redirect to Index
                return RedirectToAction("Index");

            }

            return View(ranking);
        }



        // GET: /Ranking/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ranking ranking = db.Rankings.Find(id);
            if (ranking == null)
            {
                return HttpNotFound();
            }
            return View(ranking);
        }

        // POST: /Ranking/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,First,Second,Third,Fourth,Fifth,Sixth,Seventh,Eight,Ninth,Date,BuyIn,WinFirst,WinSecond,WinThird")] Ranking ranking)
        {


            if (ModelState.IsValid)
            {
                //Problem with ObjectManger because of 2 object with the same key couldn't be handlet
                //therefor I user AsNoTracking()
                Ranking ranking1 = db.Rankings.AsNoTracking().First(p => p.ID == ranking.ID);
                
                Ranking rankingToDelete = new Ranking
                {
                    //ID= ranking1.ID,
                    First = ranking1.First,
                    Second = ranking1.Second,
                    Third = ranking1.Third,
                    Fourth = ranking1.Fourth,
                    Fifth = ranking1.Fifth,
                    Sixth = ranking1.Sixth,
                    Seventh = ranking1.Seventh,
                    Eight = ranking1.Eight,
                    BuyIn = ranking1.BuyIn,
                    Date = ranking1.Date,
                    WinFirst = ranking1.WinFirst,
                    WinSecond = ranking1.WinSecond,
                    WinThird = ranking1.WinThird
                };

                //Ranking ranktingToDelete = db.Rankings.Find(ranking.ID);

                ranking1 = null;
                
                
                db.Entry(ranking).State = EntityState.Modified;
                db.SaveChanges();

                Ranking rankingToCreate = db.Rankings.Find(ranking.ID);
                DeleteAndUpdateUserTable(rankingToDelete);
                CreateOrUpdateUserRanking(rankingToCreate);

                return RedirectToAction("Index");
            }
            return View(ranking);
        }



        // GET: /Ranking/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ranking ranking = db.Rankings.Find(id);
            if (ranking == null)
            {
                return HttpNotFound();
            }
            return View(ranking);
        }

        // POST: /Ranking/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ranking ranking = db.Rankings.Find(id);
            DeleteAndUpdateUserTable(ranking);
            db.Rankings.Remove(ranking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void CreateOrUpdateUserRanking(Ranking ranking)
        {
            //update User table
            string first = ranking.First;
            string second = ranking.Second;
            string third = ranking.Third;
            string fourth = ranking.Fourth;
            string fifth = ranking.Fifth;
            string sixth = ranking.Sixth;
            string seventh = ranking.Seventh;
            string eight = ranking.Eight;

            int firstWin = ranking.WinFirst;
            int secondWin = ranking.WinSecond;
            int thirdWin = ranking.WinThird;

            /**
            var findUser = (from m in db.Users
                           where m.Name == first
                           || m.Name == second
                           || m.Name == third
                           || m.Name == fourth
                           || m.Name == fifth
                           || m.Name == sixth
                           || m.Name == seventh
                           || m.Name == eight
                           select m).ToList();

            **/


            if (!string.IsNullOrEmpty(first))
            {

                var findUserFirst = (from m in db.Users
                                     where m.Name == first
                                     select m).ToList();

                if (findUserFirst.Count > 0)
                {

                    var user1 = db.Users.Single(u => u.Name == first);
                    user1.Input = user1.Input + ranking.BuyIn;
                    user1.Presence = user1.Presence + 1;
                    user1.Points = user1.Points + 8;
                    user1.Win = user1.Win + firstWin;


                    db.SaveChanges();
                }
                else
                {
                    User userNew = new User();
                    userNew.Name = ranking.First;
                    userNew.Presence = 1;
                    userNew.Points = 8;
                    userNew.Input = ranking.BuyIn;
                    userNew.Win = firstWin;
                    db.Users.Add(userNew);
                    db.SaveChanges();
                }
            }

            if (!string.IsNullOrEmpty(second))
            {

                var findUserSecond = (from m in db.Users
                                      where m.Name == second
                                      select m).ToList();

                if (findUserSecond.Count > 0)
                {

                    var user1 = db.Users.Single(u => u.Name == second);
                    user1.Input = user1.Input + ranking.BuyIn;
                    user1.Presence = user1.Presence + 1;
                    user1.Points = user1.Points + 7;
                    user1.Win = user1.Win + secondWin;


                    db.SaveChanges();
                }
                else
                {
                    User userNew = new User();
                    userNew.Name = ranking.Second;
                    userNew.Presence = 1;
                    userNew.Points = 7;
                    userNew.Input = ranking.BuyIn;
                    userNew.Win = secondWin;
                    db.Users.Add(userNew);
                    db.SaveChanges();
                }
            }


            if (!string.IsNullOrEmpty(third))
            {

SickFriday/SickFriday/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SickFriday.Models;

namespace SickFriday.Controllers
{
    public class UserController : Controller
    {
        private SickFridayDB db = new SickFridayDB();

        // GET: /User/
        public ActionResult Index()
        {
            return View(db.Users.ToList().OrderByDescending(c => c.Points));
        }

        // GET: /User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: /User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Name,Points,Input,Win,Presence")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: /User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Name,Points,Input,Win,Presence")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: /User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SickFriday/SickFriday/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SickFriday/SickFriday/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Roger Bollmann<br />
    Rietackstrasse 7<br />
    8610 Uster<br />
    <strong>Support:</strong>   <a href="roger.bollmann@gmail.com">roger.bollmann@gmail.com</a>
</address>

SickFriday/SickFriday/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>SickFriday</h1>
    <p class="lead">SickFriday ist eine private Poker Gruppe, welchen jeden Freitag zusammen Poker spielen</p>
    <img src="../Images/sickfriday.jpg" width="1000" height="500" />
    
    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Ranking</h2>
        <p>
            Hier kannst du eine Übersicht über alle gespielten Pokerspiele sehen
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index","Ranking")">Ranking</a></p>
    </div>
    <div class="col-md-4">
        <h2>Player</h2>
        <p>Hier kannst du eine Übersicht über die Statistik per Spieler finden</p>
        <p><a class="btn btn-default" href="@Url.Action("Index","User")">Spieler</a></p>
    </div>
    <div class="col-md-4">
        <h2>Charts</h2>
        <p>Wenn du lieber Grafiken siehst, dann bist du hier richtig</p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Charts")">Charts</a></p>
    </div>
</div>

SickFriday/SickFriday/Views/Home/Member.cshtml
@{
    ViewBag.Title = "Member";
}
<div class="page-header">
    <h2>Member</h2> <br />
    <p>
        Members kann man nur in zustimmung allen Mitgliedern werden. <br />
        Folgende Personen sind Mitglieder bei SickFriday:<br />
    </p>
</div>

<div class="row">
    <div class="col-sm-6 col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Roger</div>
            <div class="panel-body">
                <p>
                    <img src="../Images/avatar.jpg" width="100" height="100" />
                    <div><label class="control-label">Ort: Uster</label></div>
                    <div><label class="control-label">Member seit: 2013</label></div>
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Fabian</div>
            <div class="panel-body">
                <p>
                    <img src="../Images/avatar.jpg" width="100" height="100" />
                    <div><label class="control-label">Ort: Volkentswil</label></div>
                    <div><label class="control-label">Member seit: 2013</label></div>
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Mario</div>
            <div class="panel-body">
                <p>
                    <img src="../Images/avatar.jpg" width="100" height="100" />
                    <div><label class="control-label">Ort: Uster</label></div>
                    <div><label class="control-label">Member seit: 2013</label></div>
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Mäde</div>
            <div class="panel-body">
                <p>
                    <img src="../Images/avatar.jpg" width="100" height="100" />
                    <div><label class="control-label">Ort: Uster</label></div>
                    <div><label class="control-label">Member seit: 2013</label></div>
                </p>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-6 col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Andrin</div>
            <div class="panel-body">
                <p>
                    <img src="../Images/avatar.jpg" width="100" height="100" />
                    <div><label class="control-label">Ort: Uster</label></div>
                    <div><label class="control-label">Member seit: 2013</label></div>
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Yasar</div>
            <div class="panel-body">
                <p>
                    <img src="../Images/avatar.jpg" width="100" height="100" />
                    <div><label class="control-label">Ort: Uster</label></div>
                    <div><label class="control-label">Member seit: 2013</label></div>
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Sergio</div>
            <div class="panel-body">
                <p>
                    <img src="../Images/avatar.jpg" width="100" height="100" />
                    <div><label class="control-label">Ort: Uster</label></div>
                    <div><label class="control-label">Member seit: 2013</label></div>
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Rocco</div>
            <div class="panel-body">
                <p>
                    <img src="../Images/avatar.jpg" width="100" height="100" />
                    <div><label class="control-label">Ort: Uster</label></div>
                    <div><label class="control-label">Member seit: 2014</label></div>
                </p>
            </div>
        </div>
    </div>
</div>